# Generated by Django 6.0.1 on 2026-02-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone_verified_phoneotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
