# Generated by Django 6.0.1 on 2026-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_phone_verified_delete_phoneotp"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationOTP",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel", models.CharField(choices=[("email", "Email"), ("phone", "Phone")], max_length=10)),
                ("target", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=6)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [models.Index(fields=["channel", "target", "created_at"], name="accounts_re_channel_7df2ca_idx")],
            },
        ),
    ]
