# Generated by Django 6.0.1 on 2026-02-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_booking_unique_trip_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
