# Generated by Django 6.0.1 on 2026-02-03 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('trips', '0002_booking_unique_trip_rider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('trip', 'reviewer'), name='unique_review_per_trip_reviewer'),
        ),
    ]
